apiVersion: v1
data:
  default.conf: "server {\n    listen 80;\n    server_name 192.168.49.2;\n    location / {\n        proxy_pass http://web:8000/;\n    }\n} "
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx
  name: nginx-cm0
