"""empty message

Revision ID: 1ac7f7177ff1
Revises: 
Create Date: 2023-10-15 18:24:19.226406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac7f7177ff1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polarny',
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('oil', sa.Integer(), nullable=True),
    sa.Column('train_name_1', sa.String(length=100), nullable=True),
    sa.Column('train_1_unloading', sa.Integer(), nullable=True),
    sa.Column('train_name_2', sa.String(length=100), nullable=True),
    sa.Column('train_2_unloading', sa.Integer(), nullable=True),
    sa.Column('train_name_3', sa.String(length=100), nullable=True),
    sa.Column('train_3_unloading', sa.Integer(), nullable=True),
    sa.Column('calc_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raduzhny',
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('oil', sa.Integer(), nullable=True),
    sa.Column('train_name', sa.String(length=100), nullable=True),
    sa.Column('train_unloading', sa.Integer(), nullable=True),
    sa.Column('calc_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zvezda',
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('oil', sa.Integer(), nullable=True),
    sa.Column('train_name', sa.String(length=100), nullable=True),
    sa.Column('train_unloading', sa.Integer(), nullable=True),
    sa.Column('calc_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zvezda')
    op.drop_table('raduzhny')
    op.drop_table('polarny')
    # ### end Alembic commands ###
