name: CI
on:
   # События, которые запускают jobs
    push:
      branches: [ "docker" ]


# jobs запускаются параллельно, если не указана последовательность
jobs:
    # Название job вы можете назвать как угодно
  tests:
    # «Раннер» — создание изолированного окружения с последней версией Ubuntu 
    runs-on: ubuntu-latest
        # Шаги
    steps:
          # Actions от github: проверяет репозиторий, гит и т.д.
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo "Hello, world!"

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        # Проверка доступности репозитория Docker Hub для workflow
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        # Вызов сборщика контейнеров docker
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker 
        # Запуск скрипта авторизации на Docker Hub
        uses: docker/login-action@v1 
        with:
          username: stanislavgutnikov
          password: Wind0654W
      - name: Push to Docker Hub
        # Пуш образа в Docker Hub 
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: stanislavgutnikov/trains_and_oil:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 84.201.171.183 >> ~/.ssh/known_hosts

      - name: Copy repository to server
        run: |
          ls 
          #cd ..
          scp -r * gutnikov@84.201.171.183:/home/gutnikov/trains_and_oil/
          cd trains_and_oil/
          sudo docker-compose up
